version: '3.7'

services:
  monitor: &promobot
    # build: .
    image: leandro2r/promobot
    restart: always
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    shm_size: 2g
    environment:
      - DB_HOST=mongodb
      - MONGO_INITDB_ROOT_USERNAME=promobot
      - MONGO_INITDB_ROOT_PASSWORD=juliusrock
      - MONGO_INITDB_DATABASE=promobot
      - TELEGRAM_TOKEN=
      - TELEGRAM_CHAT_PASSWD=
      - KEYWORDS=
      - DELAY=10
      - MUTED=true
      - RESET_TIME=24
      - TIMEOUT=10
      - TZ=America/Sao_Paulo
    volumes:
      - .:/opt/promobot
    entrypoint: ""
    command: "tail -f /dev/null"

  monitor_ca:
    <<: *promobot
    # entrypoint: "python"
    # command: "promobot/__main__.py --region ca --urls 1"

  bot:
    <<: *promobot
    # network_mode: "host"
    volumes:
      - .:/opt/promobot
      - ${HOME}/.kube/config:/root/.kube/config:ro
    # entrypoint: "python"
    # command: "promobot/__main__.py --bot"

  mongodb:
    image: mongo:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      - TZ=America/Sao_Paulo
      - MONGO_INITDB_ROOT_USERNAME=promobot
      - MONGO_INITDB_ROOT_PASSWORD=juliusrock
      - MONGO_INITDB_DATABASE=promobot
    volumes:
      - data:/data/db

volumes:
  data:
