apiVersion: v1
kind: Namespace
metadata:
  name: rpi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cadvisor-cfg
  namespace: rpi
data:
  TZ: America/Sao_Paulo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  namespace: rpi
  labels:
    app: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cadvisor
  template:
    metadata:
      labels:
        name: cadvisor
    spec:
      containers:
        - name: cadvisor
          image: budry/cadvisor-arm:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: cadvisor-cfg
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: run
              mountPath: /var/run
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker
              readOnly: true
            - name: disk
              mountPath: /dev/disk
              readOnly: true
      volumes:
        - name: run
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /var/lib/docker
        - name: disk
          hostPath:
            path: /dev/disk

---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor-web
  namespace: rpi
  labels:
    app: cadvisor
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8080
  selector:
    name: cadvisor
